version: '3.8'

services:
  minio:
    image: bitnami/minio:latest
    container_name: bitnami_minio
    environment:
      - MINIO_ROOT_USER=minio_root
      - MINIO_ROOT_PASSWORD=minio_root
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  minio_data:
  mariadb_data: